ASOBJS = vectors.o modulecall.o op_dot_printa.o op_m_getsetdrv.o op_m_tapein.o op_f_open.o op_f_close.o op_f_read.o op_f_write.o op_f_seek.o op_f_fstat.o op_f_opendir.o op_f_readdir.o op_f_telldir.o op_f_seekdir.o op_f_getcwd.o op_f_chdir.o op_f_mkdir.o op_f_rmdir.o op_f_stat.o op_f_unlink.o op_f_chmod.o op_f_rename.o op_f_getfree.o
LIBS =
OUT = esxdos.module

all: module
include ../make.inc
